import React from 'react';
import ReactDOM from 'react-dom';
import './normalize.css';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import ReactGA from 'react-ga';
ReactGA.initialize('UA-156976179-1');
ReactGA.pageview('/');
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
